services:
  miniflux:
    image: docker.io/miniflux/miniflux:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      CREATE_ADMIN: ${CREATE_ADMIN}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    command: miniflux -debug
    restart: unless-stopped
    networks:
      - mynetwork

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    user: "0"
    working_dir: /cloudflared
    volumes:
      - ./dot_cloudflared:/cloudflared
    command: tunnel --config /cloudflared/tunnel-config.yaml run
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
