services:
  miniflux:
    image: docker.io/miniflux/miniflux:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_URL: https://miniflux.glek.net
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
      CREATE_ADMIN: ${CREATE_ADMIN}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    command: miniflux -debug
    networks:
      - miniflux

  minifluxdb:
    image: paradedb/paradedb:latest
    container_name: minifluxdb
    environment:
      POSTGRESQL_USERNAME: miniflux
      POSTGRESQL_PASSWORD: miniflux
      POSTGRESQL_DATABASE: miniflux
      POSTGRESQL_POSTGRES_PASSWORD: miniflux
    volumes:
      - minifluxdb_data:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - miniflux
    restart: always

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    user: "0"
    working_dir: /cloudflared
    volumes:
      - ./dot_cloudflared:/cloudflared
    command: tunnel --config /cloudflared/tunnel-config.yaml run
    networks:
      - miniflux

volumes:
  minifluxdb_data:
    driver: local
    driver_opts:
      type: none
      device: /db/miniflux
      o: bind
      
networks:
  miniflux:
    driver: bridge
    name: miniflux
